print("Hello World!")
print("Hello Again")
print("I like typing it")
print("This is fun.")
print("Yay! Printing")
print("I'd much rather you 'not'.")
print("I 'said' don't touch this.")
print("I am back.")